### ISSUE TITLE
Date issue?

### ISSUE THREAD

**Issue by chadhumphrey** [wenboyu2/yahoo-earnings-calendar#8]
Greetings and thank you for making this scrapper! 

I seem to be missing something that I suspect might be obvious, but since I'm realtively new to python, I seem to be overlooking it. 

`date_from = datetime.datetime.strptime( 'Jan 14 2018  10:00AM', '%b %d %Y %I:%M%p')
date_to = datetime.datetime.strptime( 'Mar 31 2018  1:00PM', '%b %d %Y %I:%M%p')
yec = YahooEarningsCalendar()
xx = yec.earnings_between(date_from, date_to)`

I'm able to capture the object xx and do what I need. However if I change the date from 14 to the 13 or 12, or make any changes to the date.  

`Traceback (most recent call last):
  File "earnings.py", line 43, in <module>
    xx = yec.earnings_between(date_from, date_to)
  File "/var/www/html/yahoo-earnings-calendar/yahoo_earnings_calendar/scraper.py", line 117, in earnings_between
    earnings_data += self.earnings_on(current_date)
  File "/var/www/html/yahoo-earnings-calendar/yahoo_earnings_calendar/scraper.py", line 79, in earnings_on
    page_data_dict = self._get_data_dict(dated_url)
  File "/var/www/html/yahoo-earnings-calendar/yahoo_earnings_calendar/scraper.py", line 31, in _get_data_dict
    '\n') if row.startswith('root.App.main = ')][0][:-1]
IndexError: list index out of range`

I'm not skilled enough in my python to figure out what that means and how to fix it? Any thoughts.

**Comment by wenboyu2** [comment]
Hi, I'm not able to reproduce this error. However, I noticed that Yahoo! recently updated their front-end data schema which broke this library. I'll be fixing it soon.

**Comment by vjtrost88** [comment]
I'm running into this error too @wenboyu2 @chadhumphrey. Using Python 2.7.15. It seems as though beyond a certain date range size it throws this error. I'm able to scrape from a few months back in time but beyond about 3 months it throws this error. Do you know the limit for how far back we can query in time? I was trying to grab data from 2007 to present day.
